import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { TranslationList } from "../components/TranslationList";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scripture</title>
        <meta name="description" content="Generated by Scripture" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="">The Scripture</a>
        </h1>
        <br />
        <TranslationList />
      </main>
    </div>
  );
};
export default Home;
